DELETE FROM products;
INSERT INTO products VALUES
(1,
'Devon Rex',
'The Devon Rex breed of cat has only been around since the 1960\'s. They have been genetically proven not to be related to the Cornish or German Rex breeds. The strange thing about the Devon Rex is the fact that they have very little "guard hair", the stiff, coarse, waterproof hairs present on most furred mammals.',
100,
200,
300,
400),
(2,
'Scottish Fold',
'The Scottish Fold (or Coupari in Canada), has a dominant genetic mutation that causes the cartilage in their ears to have a fold, sometimes even up to two or three folds! This makes their ears flop forward, giving them their distinctive appearance. ',
300,
400,
500,
600),
(3,
'Japanese Bobtail',
'Japanese bobtails are born with a rabbit-like puff tail, and some will even hop like rabbits, rather than running! In the year 1602, the Japanese government demanded that all cats be set free, to help protect the valuable silkworm fields from rodents. Buying and selling cats was illegal at the time, so Japanese bobtails were street cats.',
700,
800,
900,
100),
(4,
'Khao Manee',
'I actually own a Khao Manee, which is what prompted me to write this list. Siamese cats, with blue eyes and point coloration, are what everyone in the States considers a Siamese. In Thailand and the surrounding areas, however, the khao manee is the one and only Siamese cat. The Khao Manee (or “White Jewel”) was the royal cat breed of Old Siam. ',
200,
300,
400,
500)
